services:
  dashboard_db:
    image: postgres:16
    container_name: dashboard_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: dashboard_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - dashboard_db_data:/var/lib/postgresql/data

  dashboard_redis:
    image: redis:7.2
    container_name: dashboard-redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "myRedisCode123"]
    ports:
      - "6381:6379"
    volumes:
      - dashboard_redis_data:/data

volumes:
  dashboard_db_data:
  dashboard_redis_data:
