services:
  dashboard_db:
    image: postgres:16
    container_name: dashboard_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: dashboard_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - dashboard_db_data:/var/lib/postgresql/data

volumes:
  dashboard_db_data:
