spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dashboard_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6381
      password: myRedisCode123

  app:
    jwt:
      secret: "Xi89a6p5yrZHsyNaWCU7kIUmzMGsgvQmakUGkUSRW14268tccCGRuJVo8EZkd8/IqUL5/jtExXNnTHv2b13KMg=="
      access-expiration-ms: 3600000
      refresh-expiration-ms: 1209600000

  admin:
    fullName: Admin
    email: admindashboard@gmail.com
    password : admin123
    phoneNumber: +9946789768